// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKaxsX5dVeGwykUgaidEGoDnU2UPZDRco',
    appId: '1:520442395201:web:2b38618d8661eea72b64c0',
    messagingSenderId: '520442395201',
    projectId: 'heatguard-app',
    authDomain: 'heatguard-app.firebaseapp.com',
    storageBucket: 'heatguard-app.firebasestorage.app',
    measurementId: 'G-KLGEMZ0HK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnblnoLJ4NQt0_InpQqBywacGB4F-yx9g',
    appId: '1:520442395201:android:ce022767df344af32b64c0',
    messagingSenderId: '520442395201',
    projectId: 'heatguard-app',
    storageBucket: 'heatguard-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2YrKSqP979Z_LjF5EjsThm8CRcb0pWP8',
    appId: '1:520442395201:ios:bd1bf867dadef9e22b64c0',
    messagingSenderId: '520442395201',
    projectId: 'heatguard-app',
    storageBucket: 'heatguard-app.firebasestorage.app',
    iosBundleId: 'com.example.kavachApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2YrKSqP979Z_LjF5EjsThm8CRcb0pWP8',
    appId: '1:520442395201:ios:bd1bf867dadef9e22b64c0',
    messagingSenderId: '520442395201',
    projectId: 'heatguard-app',
    storageBucket: 'heatguard-app.firebasestorage.app',
    iosBundleId: 'com.example.kavachApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKaxsX5dVeGwykUgaidEGoDnU2UPZDRco',
    appId: '1:520442395201:web:5f7b641eda0244682b64c0',
    messagingSenderId: '520442395201',
    projectId: 'heatguard-app',
    authDomain: 'heatguard-app.firebaseapp.com',
    storageBucket: 'heatguard-app.firebasestorage.app',
    measurementId: 'G-H2KC6WY4N0',
  );
}
